### ISSUE TITLE
Prefab RevertAll resets GUID on prefab instances - possible workaround?

### ISSUE THREAD

**Issue by chrisyarbrough** [Unity-Technologies/guid-based-reference#12]
When I select Overrides > Revert All from the prefab instance inspector in the scene, an attached GuidComponent will reset its GUID to a new value. It kind of makes sense, because it resets all instance properties, but in the special case of unique IDs, this breaks all connections in GuidReferences. 

Is there any way to keep the GUID when Revert All is selected?

**Comment by william-w-armstrong** [comment]
Hmmm - very good point, but I don't think that is actually do-able unfortunately.
