### ISSUE TITLE
Having two guid references in the same component makes both references to appear the same in the drawer

### ISSUE THREAD

**Issue by xDura** [Unity-Technologies/guid-based-reference#3]
Having two guidreferences or any data structure that has more than one guidreference makes that both always display the same in the propierty drawer.

![bug1](https://user-images.githubusercontent.com/4575143/43004035-c59d2118-8c2e-11e8-91d1-30ffd5d779cd.PNG)
![bug2](https://user-images.githubusercontent.com/4575143/43004038-c99a7c16-8c2e-11e8-8307-12fedb31e395.PNG)

This happened to me in version 2018.1.6f1 I will also take a look.

Thanks

**Comment by Mark-LaCroix** [comment]
This is also the case for `List<GuidReference>` and `GuidReference[]`, in that every element will appear to be the same item (I haven't done testing to check if they are actually overwritten with the same value, however).

**Comment by william-w-armstrong** [comment]
Fixed in latest master branch.

**Comment by Mark-LaCroix** [comment]
Alright! Thanks for the great work!
